name: Deploy til UnoEuro hosting med FTPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Deploy til UnoEuro hosting via FTPS
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/
        protocol: ftp
        port: 21
        security: loose
        exclude: |
          **/.git*
          **/.git*/**
          README.md
          .github/
          .gitignore
          **/__pycache__/
        log-level: verbose