name: Deploy to Simply.com hosting

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    # Copy index.html and styles.css to root directory
    - name: Copy web files to root directory
      run: |
        cp frontend/index.html ./index.html
        cp frontend/styles.css ./styles.css
        echo "Copied web files to root directory"
      
    # Deploy to Simply.com via FTPS
    - name: Deploy to Simply.com via FTPS
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/
        protocol: ftps
        port: 21
        security: loose
        timeout: 120000
        dangerous-clean-slate: false
        exclude: |
          **/.git*
          **/.git*/**
          README.md
          .github/
          .gitignore
          **/__pycache__/
        log-level: verbose